/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewController;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NhatThanh
 */
public class Jpanelttlop extends javax.swing.JPanel {

    /**
     * Creates new form Jpanelttlop
     */
    ArrayList<Student> lisths = getDBStudent();
    ArrayList<gvcn> gvcn = getDBgvcn();
    DefaultTableModel model = new DefaultTableModel();
    private int index;
    Connection con;
    
    
    
    public Jpanelttlop() {
        initComponents();
        model = (DefaultTableModel) table.getModel();
        index = 0;
        settable();
        showdetail(index);
    }
    
    public Jpanelttlop(String paramalop) {
        
        initComponents();
        
    }
    public void showdetail(int index) {
       tfgvcn.setText(gvcn.get(index).getName());
       tftenlop.setText(gvcn.get(index).getTenlop());
       tfsdt.setText(gvcn.get(index).getSdt());
       tfdiachi.setText(gvcn.get(index).getDiachi());
    }

    public void settable() {
        model.setRowCount(0);
        for (Student x : lisths) {
            model.addRow(new Object[]{x.getID(), x.getName(), x.getLop(), x.getEmail(), x.getPhone(), x.getSex(), x.getAddress()});
        }
    }
    
    public ArrayList<Student> getDBStudent() {
        ArrayList<Student> l = new ArrayList<>();
        String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url = "jdbc:sqlserver://localhost:1433;databaseName=Quanlyhocsinh";
        String username = "sa";
        String password = "123";
        try {
            Class.forName(driver);
            con = DriverManager.getConnection(url, username, password);
            Statement st = con.createStatement();
            
            String sql1 = "SELECT STUDENT.MAHS, STUDENT.NAME, LOP.TENLOP, STUDENT.EMAIL, STUDENT.PHONE, STUDENT.GIOITINH, STUDENT.DIACHI\n" +
                            "FROM STUDENT, LOP\n" +
                            "WHERE STUDENT.MALOP=LOP.MALOP AND LOP.MALOP='" + JframeLogIn.maloplogin + "'";
            
            ResultSet rs1 = st.executeQuery(sql1);
            while (rs1.next()) {
                l.add(new Student(rs1.getString(1), rs1.getString(2),rs1.getString(3), rs1.getString(4), rs1.getString(5), rs1.getString(6), rs1.getString(7)));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return l;
    }
     
     public ArrayList<gvcn> getDBgvcn() {
        ArrayList<gvcn> l = new ArrayList<>();
        String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url = "jdbc:sqlserver://localhost:1433;databaseName=Quanlyhocsinh";
        String username = "sa";
        String password = "123";
        try {
            Class.forName(driver);
            con = DriverManager.getConnection(url, username, password);
            Statement st = con.createStatement();

            String sql1 = "SELECT GVCN.TENGVCN, LOP.TENLOP, GVCN.SDT, GVCN.DIACHI\n" +
                            "FROM GVCN, LOP\n" +
                            "WHERE GVCN.MALOP = LOP.MALOP AND LOP.MALOP='" + JframeLogIn.maloplogin + "'";
            ResultSet rs1 = st.executeQuery(sql1);
            while (rs1.next()) {
                l.add(new gvcn(rs1.getString(1), rs1.getString(2), rs1.getString(3), rs1.getString(4)));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return l;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfgvcn = new javax.swing.JTextField();
        tftenlop = new javax.swing.JTextField();
        tfsdt = new javax.swing.JTextField();
        tfdiachi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HS", "Họ và Tên", "Lớp", "Email", "SĐT", "Giới Tính", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(40);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(90);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(40);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(3).setPreferredWidth(90);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(4).setPreferredWidth(80);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(5).setPreferredWidth(40);
            table.getColumnModel().getColumn(6).setResizable(false);
            table.getColumnModel().getColumn(6).setPreferredWidth(90);
        }

        jLabel2.setText("Tên giáo viên chủ nhiệm:");

        jLabel3.setText("Lớp:");

        jLabel4.setText("Địa chỉ:");

        jLabel5.setText("Số điện thoại:");

        tfgvcn.setBackground(new java.awt.Color(240, 240, 240));
        tfgvcn.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        tfgvcn.setEnabled(false);

        tftenlop.setBackground(new java.awt.Color(240, 240, 240));
        tftenlop.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        tftenlop.setEnabled(false);

        tfsdt.setBackground(new java.awt.Color(240, 240, 240));
        tfsdt.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        tfsdt.setEnabled(false);

        tfdiachi.setBackground(new java.awt.Color(240, 240, 240));
        tfdiachi.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        tfdiachi.setEnabled(false);

        jLabel1.setText("Danh sách lớp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tftenlop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(tfgvcn, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfgvcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftenlop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        index = table.getSelectedRow();
       
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfdiachi;
    private javax.swing.JTextField tfgvcn;
    private javax.swing.JTextField tfsdt;
    private javax.swing.JTextField tftenlop;
    // End of variables declaration//GEN-END:variables
}
